# Generated by Django 2.0.7 on 2018-11-02 22:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sample_webapp', '0002_foo_geo_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='geojson',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
